name: Selenium File Download and Conversion

on:
  # Trigger this workflow on push or manually via the GitHub Actions UI
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_and_convert:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Check out the code from the GitHub repo

    - name: Set up Python 3.x
      uses: actions/setup-python@v4  # Set up Python for the workflow
      with:
        python-version: '3.x'  # Specify which Python version to use

    - name: Install dependencies
      run: |
        pip install selenium pandas openpyxl  # Install the required Python packages

    - name: Download WebDriver
      run: |
        sudo apt-get update  # Update the package list
        sudo apt-get install -y unzip curl  # Install utilities for downloading/unzipping
        curl -sS -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip  # Get the latest version of ChromeDriver
        unzip /tmp/chromedriver.zip -d /usr/local/bin/  # Unzip ChromeDriver and move it to the bin folder

    - name: Run Selenium script to download and convert file
      run: |
        python selenium_download.py  # Run the Python script to download and convert the file

    - name: Upload Excel artifact
      uses: actions/upload-artifact@v4  # Use the artifact action v4 (latest version)
      with:
        name: logs-excel-artifact  # Name of the artifact that will be uploaded
        path: ${{ github.workspace }}/logs_output_*.xlsx  # Upload the Excel file generated by the script

    - name: Clean up downloaded files
      run: |
        rm -f logs_output_*.xlsx  # Clean up the workspace by removing the generated files
